# Generated by Django 5.2.3 on 2025-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('availability', models.CharField(help_text='e.g. Mon-Fri, 10 AM - 6 PM', max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
