# Generated by Django 5.2.13 on 2026-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('total_marks', models.IntegerField()),
            ],
        ),
    ]
